%% Import data from text file.
% Script for importing data from the following text file:
%
%    /home/mat/adni/data/allele/v2_trace_3_alleles.csv
%
% To extend the code to different selected data or a different text file,
% generate a function instead of a script.

% Auto-generated by MATLAB on 2015/01/12 02:31:59

%% Initialize variables.
filename = '/home/mat/adni/data/allele/v2_trace_3_alleles.csv';
delimiter = '\t';
startRow = 2;

%% Format string for each line of text:
%   column1: double (%f)
%	column2: text (%s)
%   column3: double (%f)
%	column4: text (%s)
%   column5: double (%f)
%	column6: double (%f)
%   column7: double (%f)
%	column8: double (%f)
%   column9: double (%f)
%	column10: double (%f)
%   column11: double (%f)
%	column12: text (%s)
%   column13: double (%f)
%	column14: text (%s)
%   column15: double (%f)
%	column16: text (%s)
%   column17: double (%f)
%	column18: text (%s)
%   column19: double (%f)
%	column20: text (%s)
%   column21: double (%f)
%	column22: text (%s)
%   column23: double (%f)
%	column24: text (%s)
%   column25: double (%f)
%	column26: text (%s)
%   column27: double (%f)
%	column28: text (%s)
%   column29: double (%f)
% For more information, see the TEXTSCAN documentation.
formatSpec = '%f%s%f%s%f%f%f%f%f%f%f%s%f%s%f%s%f%s%f%s%f%s%f%s%f%s%f%s%f%[^\n\r]';

%% Open the text file.
fileID = fopen(filename,'r');

%% Read columns of data according to format string.
% This call is based on the structure of the file used to generate this
% code. If an error occurs for a different file, try regenerating the code
% from the Import Tool.
dataArray = textscan(fileID, formatSpec, 'Delimiter', delimiter, 'HeaderLines' ,startRow-1, 'ReturnOnError', false);

%% Close the text file.
fclose(fileID);

%% Post processing for unimportable data.
% No unimportable data rules were applied during the import, so no post
% processing code is included. To generate code which works for
% unimportable data, select unimportable cells in a file and regenerate the
% script.

%% Allocate imported array to column variable names
FID = dataArray{:, 1};
IID = dataArray{:, 2};
bin = dataArray{:, 3};
cat1 = dataArray{:, 4};
pp = dataArray{:, 5};
pc = dataArray{:, 6};
gc = dataArray{:, 7};
sex = dataArray{:, 8};
age = dataArray{:, 9};
weight = dataArray{:, 10};
race = dataArray{:, 11};
rs1501228 = dataArray{:, 12};
rs1501228_code = dataArray{:, 13};
rs12565755 = dataArray{:, 14};
rs12565755_code = dataArray{:, 15};
rs12408850 = dataArray{:, 16};
rs12408850_code = dataArray{:, 17};
rs1946867 = dataArray{:, 18};
rs1946867_code = dataArray{:, 19};
rs3905886 = dataArray{:, 20};
rs3905886_code = dataArray{:, 21};
rs9951577 = dataArray{:, 22};
rs9951577_code = dataArray{:, 23};
rs4149286 = dataArray{:, 24};
rs4149286_code = dataArray{:, 25};
rs343248 = dataArray{:, 26};
rs343248_code = dataArray{:, 27};
rs4149284 = dataArray{:, 28};
rs4149284_code = dataArray{:, 29};


%% Clear temporary variables
clearvars filename delimiter startRow formatSpec fileID dataArray ans;